
graph TD
  HOME --> StartHere
  HOME --> BuyingSilver
  HOME --> PricesTools
  HOME --> Education
  HOME --> Storage
  HOME --> Articles
  HOME --> Email
  HOME --> About

  StartHere --> WhatIsSilver
  StartHere --> SpotVsPremium
  StartHere --> CoinsVsBars

  BuyingSilver --> BestPlaces
  BuyingSilver --> CheapestPerOunce
  BuyingSilver --> CompareDealers

  PricesTools --> LiveSpot
  PricesTools --> PremiumCalculator
  PricesTools --> StackValue






